import { test, expect } from 'claude-code/testing'
import { harness, start } from '../fake-claudish'
import { mountBand, SURFACES } from '../ui'
import { POLL, GRACE, delegate, delivered, drawingText, entries, modelCall, row, stateColor, textOf } from './support'

for (const surface of SURFACES) {
  test(`ext delegation: row and live counters [${surface}]`, async ($, on) => {
    const h = harness(on)
    await start($, surface)
    const s = await delegate($, h)
    const b = await mountBand($, surface)
    expect(await drawingText(b)).toContain('haiku-4.5')
    expect(await drawingText(b)).toContain(`#${s.id.slice(0, 6)}`)
    expect(await drawingText(b)).not.toContain(s.id)
    const before = textOf(await row(b, s.model))
    h.fake.set(s.id, s.id, 'RUNNING', null, { turnsCompleted: 1 }) // the fake pins a session at 0 loops
    await h.clock.advance(12_000)
    await b.redraw()
    const after = textOf(await row(b, s.model))
    expect(after).not.toBe(before)
    expect(after).toContain('4 tools')
    expect(after).toContain('1 loops')
    stateColor(await row(b, s.model), '▶ running', 'warning')
    expect(h.submits).toHaveLength(0)
    expect(h.fake.captureCalls()).toHaveLength(0)
    await b.unmount()
  })

  test(`ext delegation: promptless first wait, same wait, new wait, then completion [${surface}]`, async ($, on) => {
    const h = harness(on)
    await start($, surface)
    // Promptless create starts waiting in the supplied contract fake.
    const s = await delegate($, h, null)
    const b = await mountBand($, surface)
    stateColor(await row(b, s.model), '◇ input', 'permission')
    expect(h.submits).toHaveLength(0)
    await h.clock.advance(GRACE + POLL)
    expect(h.submits).toHaveLength(1)
    expect(h.submits[0]).toContain(s.id)
    expect(h.submits[0]).toContain('get_output')
    expect(h.submits[0]).toContain('send_input')
    expect(h.toasts.filter(t => /waiting for input/.test(t))).toHaveLength(1)
    await h.clock.advance(30_000)
    expect(h.submits).toHaveLength(1)
    await modelCall($, 'mcp__plugin_claudish_claudish__send_input', { session_id: s.id, input: 'Continue' })
    await h.clock.advance(POLL)
    h.fake.set(s.id, s.id, 'AWAITING_INPUT', null, { turnsCompleted: 1, activity: null })
    await h.clock.advance(POLL + GRACE + POLL)
    expect(h.submits).toHaveLength(2)
    h.fake.set(s.id, s.id, 'COMPLETED')
    await h.clock.advance(POLL + GRACE + POLL)
    expect(h.submits).toHaveLength(3)
    expect(h.submits[2]).toContain('COMPLETED')
    expect(h.submits[2]).toContain('get_output')
    expect(delivered(h)).toHaveLength(3)
    await h.clock.advance(30_000)
    expect(h.submits).toHaveLength(3)
    await b.redraw()
    stateColor(await row(b, s.model), '✓ done', 'success')
    expect(await b.findAll({ type: 'Button', text: /^Stop$/ })).toHaveLength(0)
    await b.unmount()
  })

  test(`ext delegation: permission and question are distinct wait entries [${surface}]`, async ($, on) => {
    const h = harness(on)
    await start($, surface)
    const s = await delegate($, h)
    const b = await mountBand($, surface)
    h.fake.set(s.id, s.id, 'AWAITING_PERMISSION', null, { activity: 'Bash' })
    await h.clock.advance(POLL + GRACE + POLL)
    expect(h.submits).toHaveLength(1)
    expect(h.submits[0]).toMatch(/permission dialog/)
    await b.redraw()
    stateColor(await row(b, s.model), '◇ permit', 'permission')
    h.fake.set(s.id, s.id, 'RUNNING')
    await h.clock.advance(POLL)
    h.fake.set(s.id, s.id, 'AWAITING_INPUT', null, { activity: 'AskUserQuestion', turnsCompleted: 1 })
    await h.clock.advance(POLL + GRACE + POLL)
    expect(h.submits).toHaveLength(2)
    expect(h.submits[1]).toMatch(/asking a question.*waiting for an answer/)
    await h.clock.advance(30_000)
    expect(h.submits).toHaveLength(2)
    expect(delivered(h)).toHaveLength(2)
    await b.unmount()
  })

  test(`ext delegation: answered during hold still reports the owed wait honestly [${surface}]`, async ($, on) => {
    const h = harness(on)
    await start($, surface)
    const s = await delegate($, h)
    h.fake.set(s.id, s.id, 'AWAITING_INPUT', null, { activity: null })
    await h.clock.advance(POLL)
    expect(entries(h)).toHaveLength(1)
    await modelCall($, 'mcp__plugin_claudish_claudish__send_input', { session_id: s.id, input: 'Continue' })
    await h.clock.advance(POLL + GRACE + POLL)
    expect(h.submits).toHaveLength(1)
    expect(h.submits[0]).toMatch(/waited for input; now RUNNING/)
    expect(delivered(h)).toHaveLength(1)
  })

  test(`ext delegation: wait and terminal share one honest slot line at turn end [${surface}]`, async ($, on) => {
    const h = harness(on)
    await start($, surface)
    const s = await delegate($, h)
    await $.turn.start({ text: 'Still working', turnId: 'ext-main' })
    h.fake.set(s.id, s.id, 'AWAITING_INPUT', null, { activity: null })
    await h.clock.advance(POLL)
    h.fake.set(s.id, s.id, 'COMPLETED')
    await h.clock.advance(POLL + GRACE + POLL)
    expect(h.submits).toHaveLength(0)
    await $.turn.complete({ answer: 'Done', durationMs: 1, isAborted: false, reason: 'answer', turnId: 'ext-main' })
    await h.clock.settle()
    expect(h.submits).toHaveLength(0) // held after the turn: the monitor line a turn queues arrives only after it
    await h.clock.advance(GRACE + POLL)
    expect(h.submits).toHaveLength(1)
    expect(h.submits[0]).toMatch(/COMPLETED.*had been waiting for input/)
    expect(h.submits[0]!.split('\n').filter(l => /^\s*- /.test(l))).toHaveLength(1)
    expect(delivered(h)).toHaveLength(2)
  })
}
