import { test, expect } from 'claude-code/testing'
import { harness, start } from '../fake-claudish'
import { mountBand, SURFACES, walk } from '../ui'
import { POLL, GRACE, button, delegate, drawingText, press, row, stateColor, team, textOf } from './support'

for (const surface of SURFACES) {
  test(`ext Stop: first press only arms, is primary, and expires at four seconds [${surface}]`, async ($, on) => {
    const h = harness(on)
    await start($, surface)
    const r = await team($, h)
    const b = await mountBand($, surface)
    await press(b, 'model-a', 'Stop')
    expect(h.fake.cancelCalls()).toHaveLength(0)
    await b.redraw()
    const confirm = await b.find({ type: 'Button', text: /^confirm\?$/ })
    expect(confirm?.props.variant).toBe('primary')
    expect(confirm?.props.color).toBeUndefined()
    await h.clock.advance(3_999)
    await b.redraw()
    expect(textOf(await row(b, 'model-a'))).toContain('confirm?')
    await h.clock.advance(1)
    await b.redraw()
    expect(textOf(await row(b, 'model-a'))).not.toContain('confirm?')
    expect(await button(b, 'model-a', 'Stop')).toBeDefined()
    await h.clock.advance(1_000)
    expect(h.fake.cancelCalls()).toHaveLength(0)
    expect(r.slots.every(s => s.control.state === 'RUNNING')).toBe(true)
    await b.unmount()
  })

  test(`ext Stop: confirm targets exactly one slot and run id; stopped still wakes [${surface}]`, async ($, on) => {
    const h = harness(on)
    await start($, surface)
    const r = await team($, h)
    const b = await mountBand($, surface)
    await press(b, 'model-b', 'Stop')
    await b.redraw()
    await press(b, 'model-b', 'confirm?')
    expect(h.fake.cancelCalls()).toHaveLength(1)
    expect(h.fake.cancelCalls()[0]).toMatchObject({ tool: 'team', server: 'plugin:claudish:claudish', args: { mode: 'cancel', path: r.path, run_id: r.runId, slot: '02' } })
    expect(Object.keys(h.fake.cancelCalls()[0]!.args).sort()).toEqual(['mode', 'path', 'run_id', 'slot'])
    expect(r.slots.map(s => s.control.state)).toEqual(['RUNNING', 'CANCELLED', 'RUNNING'])
    await h.clock.advance(POLL)
    await b.redraw()
    stateColor(await row(b, 'model-b'), '■ stopped', 'inactive')
    expect(walk(await row(b, 'model-b')).filter(x => x.node.type === 'Button' && x.node.props?.label === 'Stop')).toHaveLength(0)
    expect(h.submits).toHaveLength(1)
    expect(h.submits[0]).toContain('stopped by the person')
    await h.clock.advance(20_000)
    expect(h.fake.cancelCalls()).toHaveLength(1)
    expect(h.submits).toHaveLength(1)
    await b.unmount()
  })

  test(`ext Stop: delegation uses session_id, not a team or pane address [${surface}]`, async ($, on) => {
    const h = harness(on)
    await start($, surface)
    const s = await delegate($, h)
    const b = await mountBand($, surface)
    await press(b, s.model, 'Stop')
    await b.redraw()
    await press(b, s.model, 'confirm?')
    expect(h.fake.cancelCalls()).toHaveLength(1)
    expect(h.fake.cancelCalls()[0]).toMatchObject({ tool: 'cancel_session', args: { session_id: s.id } })
    expect(Object.keys(h.fake.cancelCalls()[0]!.args)).toEqual(['session_id'])
    await h.clock.advance(POLL + GRACE + POLL)
    await b.redraw()
    stateColor(await row(b, s.model), '■ stopped', 'inactive')
    expect(h.submits).toHaveLength(1)
    expect(h.submits[0]).toContain('stopped by the person')
    await b.unmount()
  })

  test(`ext Stop: concurrent confirm presses can send only one cancel [${surface}]`, async ($, on) => {
    const h = harness(on)
    await start($, surface)
    await team($, h)
    const b = await mountBand($, surface)
    await press(b, 'model-a', 'Stop')
    await b.redraw()
    const key = await button(b, 'model-a', 'confirm?')
    await Promise.all([b.press({ key }), b.press({ key })])
    expect(h.fake.cancelCalls()).toHaveLength(1)
    await b.unmount()
  })

  test(`ext Stop: arms are per slot; a press at the deadline starts a fresh arm [${surface}]`, async ($, on) => {
    const h = harness(on)
    await start($, surface)
    const r = await team($, h)
    const b = await mountBand($, surface)
    await press(b, 'model-a', 'Stop')
    await h.clock.advance(2_000)
    await b.redraw()
    await press(b, 'model-b', 'Stop')
    await h.clock.advance(2_000)
    await b.redraw()
    await press(b, 'model-a', 'Stop')
    expect(h.fake.cancelCalls()).toHaveLength(0)
    await b.redraw()
    expect(await b.findAll({ type: 'Button', text: /^confirm\?$/ })).toHaveLength(2)
    await press(b, 'model-b', 'confirm?')
    expect(h.fake.cancelCalls().map(c => c.args.slot)).toEqual(['02'])
    expect(r.slots[0]!.control.state).toBe('RUNNING')
    await b.unmount()
  })

  for (const [name, options] of [
    ['ContractError', { cancelError: 'unknown_slot' }],
    ['permission denial', { denyCancel: 'person answered No' }],
  ] as const) {
    test(`ext Stop: ${name} clears confirmation and does not claim a person stop [${surface}]`, async ($, on) => {
      const h = harness(on, options)
      await start($, surface)
      const r = await team($, h)
      const b = await mountBand($, surface)
      await press(b, 'model-a', 'Stop')
      await b.redraw()
      await press(b, 'model-a', 'confirm?')
      await b.redraw()
      expect(await button(b, 'model-a', 'Stop')).toBeDefined()
      expect(h.toasts.some(t => /Stop failed/.test(t))).toBe(true)
      expect(r.slots[0]!.control.state).toBe('RUNNING')
      h.fake.set(r.runId, '01', 'CANCELLED', 'cancelled')
      await h.clock.advance(POLL)
      expect(h.submits).toHaveLength(1)
      expect(h.submits[0]).not.toContain('stopped by the person')
      await b.unmount()
    })
  }

  test(`ext Stop: changed:false cannot credit the person for an already-ended slot [${surface}]`, async ($, on) => {
    const h = harness(on)
    await start($, surface)
    const r = await team($, h)
    const b = await mountBand($, surface)
    await press(b, 'model-a', 'Stop')
    await b.redraw()
    // No poll between the outside cancellation and the person's second press.
    h.fake.set(r.runId, '01', 'CANCELLED', 'cancelled')
    await press(b, 'model-a', 'confirm?')
    expect(h.fake.cancelCalls()).toHaveLength(1)
    await h.clock.advance(POLL)
    expect(h.submits).toHaveLength(1)
    expect(h.submits[0]).not.toContain('stopped by the person')
    await b.unmount()
  })

  test(`ext Stop: held permission/cancel answer cannot send twice or time out [${surface}]`, async ($, on) => {
    const h = harness(on)
    await start($, surface)
    await team($, h)
    const b = await mountBand($, surface)
    await press(b, 'model-a', 'Stop')
    await b.redraw()
    const key = await button(b, 'model-a', 'confirm?')
    const gate = h.fake.holdCancels()
    const pending = b.press({ key })
    await h.clock.settle()
    expect(h.fake.cancelCalls()).toHaveLength(1)
    await h.clock.advance(25_000)
    await b.redraw()
    expect(textOf(await row(b, 'model-a'))).not.toContain('confirm?')
    expect(walk(await row(b, 'model-a')).some(x => x.node.type === 'Button' && x.node.props?.label === 'Stop')).toBe(false)
    expect(h.toasts.some(t => /Stop not confirmed/.test(t))).toBe(false)
    gate.release()
    await pending
    await h.clock.advance(POLL)
    await b.redraw()
    expect(await drawingText(b)).toContain('■ stopped')
    expect(h.fake.cancelCalls()).toHaveLength(1)
    await b.unmount()
  })

  test(`ext Stop: absent cancel capability offers no Stop, but keeps Show [${surface}]`, async ($, on) => {
    const h = harness(on, { noCancel: true })
    await start($, surface)
    await team($, h)
    const b = await mountBand($, surface)
    expect(await b.findAll({ type: 'Button', text: /^Stop$/ })).toHaveLength(0)
    expect(await b.findAll({ type: 'Button', text: /^Show$/ })).toHaveLength(3)
    expect(h.fake.cancelCalls()).toHaveLength(0)
    await b.unmount()
  })
}
