import { test, expect } from 'claude-code/testing'
import { harness, start, TEAM_TOOL } from '../fake-claudish'
import { mountBand, SURFACES } from '../ui'
import { POLL, GRACE, team, delivered, drawingText, endTurn, modelCall, row, stateColor } from './support'

for (const surface of SURFACES) {
  test(`ext team: every slot ends once; final settle waits for the monitor [${surface}]`, async ($, on) => {
    const h = harness(on)
    await start($, surface)
    const r = await team($, h)
    const b = await mountBand($, surface)
    expect(await b.findAll({ type: 'Button', text: /^Show$/ })).toHaveLength(3)
    expect(await b.findAll({ type: 'Button', text: /^Stop$/ })).toHaveLength(3)
    expect(await drawingText(b)).toContain('3 running')
    const states = ['COMPLETED', 'FAILED', 'CANCELLED']
    const reasons = [null, 'blocked', 'cancelled']
    for (let i = 0; i < r.slots.length; i++) {
      h.fake.set(r.runId, r.slots[i]!.slot, states[i]!, reasons[i])
      await h.clock.advance(POLL)
      if (i < 2) {
        expect(h.submits).toHaveLength(i + 1)
        expect(h.submits[i]).toContain(`slot ${r.slots[i]!.slot}`)
        expect(h.submits[i]).toContain(states[i])
        expect(h.submits[i]).toContain(r.runId)
        expect(h.submits[i]).toContain(r.path)
        expect(h.submits[i]).toContain('still running:')
      } else {
        expect(h.submits).toHaveLength(2)
        await h.clock.advance(GRACE + POLL)
        expect(h.submits).toHaveLength(3)
        expect(h.submits[2]).toContain('CANCELLED')
        expect(h.submits[2]).not.toContain('still running:')
      }
      await h.clock.advance(POLL)
      expect(h.submits).toHaveLength(i + 1)
    }
    expect(delivered(h)).toHaveLength(3)
    expect(h.toasts).toHaveLength(3)
    expect(h.submits[1]).toContain('blocked')
    expect(h.submits.every(s => s.includes('team(mode="status"'))).toBe(true)
    await b.redraw()
    stateColor(await row(b, 'model-a'), '✓ done', 'success')
    stateColor(await row(b, 'model-b'), '✕ failed', 'error')
    stateColor(await row(b, 'model-c'), '■ stopped', 'inactive')
    expect(await b.findAll({ type: 'Button', text: /^Stop$/ })).toHaveLength(0)
    await h.clock.advance(60_000)
    await b.redraw()
    expect(h.submits).toHaveLength(3)
    expect(await b.findAll({ type: 'Button', text: /^Show$/ })).toHaveLength(3)
    await b.unmount()
  })

  test(`ext team: running main turn defers and coalesces; subagent completion does not flush [${surface}]`, async ($, on) => {
    const h = harness(on)
    await start($, surface)
    const r = await team($, h)
    await $.turn.start({ text: 'Main is working', turnId: 'ext-main' })
    h.fake.set(r.runId, '01', 'COMPLETED')
    await h.clock.advance(POLL)
    h.fake.set(r.runId, '02', 'FAILED', 'api_error')
    await h.clock.advance(POLL)
    expect(h.toasts).toHaveLength(2)
    expect(h.submits).toHaveLength(0)
    await endTurn($, 'child-agent')
    await h.clock.settle()
    expect(h.submits).toHaveLength(0)
    await endTurn($)
    await h.clock.settle()
    expect(h.submits).toHaveLength(1)
    expect(h.submits[0]).toContain('slot 01')
    expect(h.submits[0]).toContain('slot 02')
    expect(h.submits[0]).toContain('still running: 03')
    expect(delivered(h)).toHaveLength(2)
    await endTurn($)
    await h.clock.settle()
    await h.clock.advance(POLL)
    expect(h.submits).toHaveLength(1)
  })

  test(`ext team: rejected submit is retried, parked, and retried at main turn end [${surface}]`, async ($, on) => {
    const h = harness(on)
    await start($, surface)
    const r = await team($, h)
    h.submitAnswer = () => ({ drop: 'policy refused' })
    h.fake.set(r.runId, '01', 'COMPLETED')
    await h.clock.advance(POLL)
    expect(h.attempts).toHaveLength(1)
    expect(delivered(h)).toHaveLength(0)
    await h.clock.advance(28_000) // the first attempt lands at a tick inside POLL, so keep a margin
    expect(h.attempts).toHaveLength(1)
    await h.clock.advance(3_000)
    expect(h.attempts).toHaveLength(2)
    await h.clock.advance(61_000)
    expect(h.attempts).toHaveLength(3)
    expect(h.submits).toHaveLength(0)
    expect(h.statuses.some(t => t?.includes('waiting to be delivered'))).toBe(true)
    h.submitAnswer = text => ({ text })
    await endTurn($)
    await h.clock.settle()
    expect(h.attempts).toHaveLength(4)
    expect(h.submits).toHaveLength(1)
    expect(delivered(h)).toHaveLength(1)
    expect(h.statuses[h.statuses.length - 1]).toBeUndefined()
    await h.clock.advance(11 * 60_000)
    expect(h.submits).toHaveLength(1)
  })

  test(`ext team: same path is a new generation, not an old delivered transition [${surface}]`, async ($, on) => {
    const h = harness(on)
    await start($, surface)
    const first = await team($, h, 'review', ['round-one'])
    h.fake.set(first.runId, '01', 'COMPLETED')
    await h.clock.advance(POLL + GRACE + POLL)
    const second = await team($, h, 'review', ['round-two'])
    expect(second.runId).not.toBe(first.runId)
    const b = await mountBand($, surface)
    expect(await drawingText(b)).toContain('review·2')
    h.fake.set(second.runId, '01', 'COMPLETED')
    await h.clock.advance(POLL + GRACE + POLL)
    expect(h.submits).toHaveLength(2)
    expect(h.submits[0]).toContain(first.runId)
    expect(h.submits[1]).toContain(second.runId)
    expect(h.submits[1]).toContain('review·2')
    expect(delivered(h)).toHaveLength(2)
    await b.unmount()
  })

  test(`ext team: model-inspected and model-cancelled slots still wake [${surface}]`, async ($, on) => {
    const h = harness(on)
    await start($, surface)
    const r = await team($, h)
    await modelCall($, TEAM_TOOL, { mode: 'cancel', path: r.path, run_id: r.runId, slot: '01' })
    await modelCall($, TEAM_TOOL, { mode: 'status', path: r.path, run_id: r.runId })
    await h.clock.advance(POLL)
    expect(h.submits).toHaveLength(1)
    expect(h.submits[0]).toContain('CANCELLED')
    expect(h.submits[0]).not.toContain('stopped by the person')
    await h.clock.advance(20_000)
    expect(h.submits).toHaveLength(1)
  })
}
